export const REQUEST_TOKEN = 'auth/REQUEST_TOKEN';
export const REQUEST_SIGN_OUT = 'auth/REQUEST_SIGN_OUT';
export const REQUEST_SIGN_UP = 'auth/REQUEST_SIGN_UP';
export const REQUEST_AUTH_REMOVE_ERRORS = 'auth/REQUEST_AUTH_REMOVE_ERRORS';
export const REQUEST_SET_AUTH_ERROR = 'auth/REQUEST_SET_AUTH_ERROR';
export const SET_USER_LOADING_DONE = 'auth/SET_USER_LOADING_DONE';

export const REQUEST_ADD_PRODUCT = 'products/REQUEST_ADD_PRODUCT';
export const REQUEST_REMOVE_PRODUCT = 'products/REQUEST_REMOVE_PRODUCT';
export const REQUEST_EDIT_PRODUCT = 'products/REQUEST_EDIT_PRODUCT';
export const REQUEST_PRODUCTS = 'products/REQUEST_PRODUCTS';
export const SET_PRODUCTS_LOADED = 'products/SET_PRODUCTS_LOADED';